[Unit]
Requires=notepatch-frp-direct-route.service
After=notepatch-frp-direct-route.service

[Service]
Environment="HTTP_PROXY="
Environment="HTTPS_PROXY="
Environment="ALL_PROXY="
Environment="NO_PROXY=8.137.78.255,localhost,127.0.0.1"
